version: '1.0'
stages:
  - checkout
  - package
  - deploy  
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  BuildingDockerImage:
    title: Building Docker Image
    type: build
    image_name: my-flask-app
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
    stage: package
  DeployMyChart:
    image: 'codefresh/cfstep-helm:3.0.3'
    title: Deploying Helm chart
    stage: deploy
    environment:
      - CHART_REF=charts/python
      - RELEASE_NAME=mypython-chart-prod
      - KUBE_CONTEXT=rb-kube-cluster 
      - VALUE_image_repository=r.cfcr.io/jvergara-codefresh/my-flask-app
      - VALUE_image_pullPolicy=Always
      - VALUE_image_tag='${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
      - VALUE_buildID='${{CF_BUILD_ID}}'
      - VALUE_image_pullSecret=codefresh-generated-r.cfcr.io-cfcr-default
